Release/0.6.0
snowplow/dataflow-runner pull request #69
Opened 2021-07-19 15:57 UTC by oguzhanunlu

2021-07-20 06:14 UTC, oguzhanunlu commented
todo: use this strategy only if rate limit is hit

2021-07-23 08:19 UTC, chuwy requested changes
Overall looks good now, but would like to make sure we capture the throughput exception to give a green tick.

2021-07-23 08:52 UTC, chuwy commented
> todo: use this strategy only if a rate limit exception is captured in err

Actually, sorry. To be clear - this reverse backoff period is for normally functioning clusters. It's fairly unrelated to the initial issue we had.

Once the throughput exceptions is thrown - we should not decrease it... maybe even increase back.

Also, make sure we catch only those errors, nothing else should push back the failure.

1. Reverse backoff is to start cluster sooner. Very small improvement
2. Catching throughput is overcome the original problem

2021-08-02 16:15 UTC, oguzhanunlu commented
new logic is not tested yet

2021-08-16 11:12 UTC, chuwy approved these changes
Hey @oguzhanunlu. Generally looks good - I'm just wondering if we can move the new logic (or part of it) into a separate procedure. I don't feel comfortable about 80 LoC functions.

2021-08-16 11:16 UTC, oguzhanunlu commented
Thanks @chuwy , of course, I'll move it

2021-10-18 09:05 UTC, oguzhanunlu commented
sure, I'll address both feedback

2022-01-12 09:06 UTC, dilyand approved these changes
👍🏻

2022-01-12 09:15 UTC, oguzhanunlu commented on src/job_flow_steps.go
> +			time.Sleep(time.Second * 15)
That will help in case some future author calls `JobFlowSteps.GetFailedStepIDs` without waiting on cluster termination like we wait in this PR

2022-01-19 15:16 UTC, merged